version: 0.1
phases:
  install:
    commands:
      - echo no os dependencies required
  pre_build:
    commands:
      - echo no pre_build commands
  build:
    commands:
      - pip install -r requirements.txt
      - pip install aws-cli --upgrade
      -aws cloudformation package --template-file template.yml --output-template-file template_post.yml --s3-bucket s3tempbucket-s3bucket-bg5uudpuhi3h
  post_build:
    commands:
      - echo Build completed on `date`